#### 1. Import the numpy package under the name `np` (★☆☆)

## 2. Create a null vector of size 10 (★☆☆)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5.  Reverse a vector (first element becomes last) (★☆☆)将上题的向量倒序显示

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)创建一个3x3矩阵，其值范围为0到8

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)查找\[1,2,0,0,4,0\]中非零元素的索引
提示：使用np.nonzero方法

(array([0, 1, 4], dtype=int64),)


#### 8. Create a 3x3 identity matrix (★☆☆)对角矩阵

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 9. Create a 3x3x3 array with random values (★☆☆)创建具有随机值的3x3x3数组

[[[0.38623687 0.72860689 0.11861256]
  [0.87583184 0.75984112 0.92027858]
  [0.15569262 0.24601167 0.40514924]]

 [[0.23179978 0.41058658 0.97117928]
  [0.76418077 0.5534301  0.52208481]
  [0.6620278  0.92392492 0.58433957]]

 [[0.14777566 0.83096875 0.20888782]
  [0.94630753 0.14862539 0.88969933]
  [0.10930963 0.13027745 0.41575222]]]


#### 10. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)创建一个具有随机值的10x10数组，并找到最小值和最大值

0.004334784341918696 0.9914238367397242


#### 11. Create a random vector of size 30 and find the mean value (★☆☆)

0.5720815414833132


#### 12. Create a 2d array with 1 on the border and 0 inside (★☆☆)创建一个二维矩阵，边届是1，内部是0，提示先建矩阵再用切片修改值

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 13. Create a 4x4 matrix with values 1,2,3,4 just the diagonal (★☆☆)创建一个5x5矩阵，对角线1,2,3,4

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 14. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)创建8x8矩阵并用棋盘矩阵

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 15. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)将5x3全1矩阵乘以3x2全1矩阵（实矩阵乘积）
提示： np.dot

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 16. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)生成一个10个元素的1D数组，对下标为3到8之间的所有元素的反（正数变负数，负数变正数）

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 17. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)创建一个5x5矩阵，行值范围为0到4

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 18. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)创建一个大小为10的向量，其值范围为0到1

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 19. Create a random vector of size 10 and sort it (★★☆)创建一个大小为10的随机向量并对其进行排序

[0.10181103 0.26965266 0.28134397 0.39484134 0.41394065 0.4810561
 0.62636945 0.74893964 0.88528826 0.97455845]


#### 20. How to convert a float (32 bits) array into an integer (32 bits) in place?创建一个大小个数为10的浮点向量，将浮点（32位）数组就地转换为整数（32位）？

[0 1 2 3 4 5 6 7 8 9]
